import Head from "next/head"
import Image from "next/image"
import Link from "next/link"
import ContactsList from "../components/ContactsList.tsx"
import styles from "../styles/Home.module.css"

export default function Home() {
  return (
    <div>
      <Head>
        <title>Contacts</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;400;500"
          rel="stylesheet"
        ></link>
      </Head>
      <main>
        <h1>Your Contacts</h1>
        <ContactsList />
        <Link href="/add">
          <a className="link">Add new contact</a>
        </Link>
      </main>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
