import Head from 'next/head'
import Link from 'next/link'
import ContactsList from '../components/ContactsList'

export default function Contacts() {
  return (
    <div>
      <Head>
        <title>Contacts</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;400;500"
          rel="stylesheet"
        ></link>
      </Head>
      <main>
        <h1>Your Contacts</h1>
        <ContactsList />
        <Link href="/add">
          <a className="link">Add new contact</a>
        </Link>
      </main>
    </div>
  )
}
